/// <reference types="cypress" />

it("Prueba commands Gmail", () => {

    cy.visit('mail.google.com')
    cy.get('#\:mm > div > div').click()
    cy.get('#\:11i').type('alexis.jeriha@gmail.com')
    cy.get('#\:110').type('Cypress Execution')
    cy.get('#\:126').type('This is a mail generated by Cypress')
    cy.get('#\:10q').click()

})
